/*
 *    This file is part of Utfx.
 *
 *    Utfx is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Utfx is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Utfx.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef UTFX_DECODER_HPP
#define UTFX_DECODER_HPP

namespace utfx {

	/** A UTF-8, UTF-16 or UTF-32 decoder.
	 * Initialized to UTF-8.
	 * @ingroup utfx
	 */

	class Decoder {
		public:
			/** An error generated by the decoder.
			 * @ingroup utfx
			 */
			class Error {
				private:
					const char * what_msg;
				public:
					/** Initializes an error with an error message.
					 * @param what_msg The error message. */
					Error(const char * what_msg) noexcept;
					/** Returns the error message */
					const char * What(void) const noexcept;
			}; /* class Error */
			/** The mode of the decoder.
			 * This affects how the data will be encoded when it is written
			 * and read from the decoder.
			 */
			enum class Mode {
				UTF8,
				UTF16_LE,
				UTF16_BE,
				UTF32_LE,
				UTF32_BE };
			/** Describes whether the decoder is reading input or writing output */
			enum class State {
				Reading,
				Writing };
		private:
			/** A pointer to the decoder structure */
			void * decoder_ptr;
		public:
			Decoder(void);
			/** Intiializes the decoder with the specified mode.
			 * @param mode The mode to initialize the decoder in
			 * */
			Decoder(Mode mode);
			/** Returns the current mode of the decoder.
			 * @returns The current mode of the decoder. */
			Mode GetMode(void) const noexcept;
			/** Returns the current state of the decoder.
			 * @returns The current state of the decoder. */
			State GetState(void) const noexcept;
			/** Returns the last decoded character.
			 * Puts the decoder back into read read mode.
			 * Note that this function may throw a @ref Error.
			 * @returns The last decoded character.
			 * */
			char32_t Read(void);
			/** Sets the mode of the decoder.
			 * @param mode The new mode of the decoder.
			 * */
			void SetMode(Mode mode) noexcept;
			/** Writes data to the decoder.
			 * @param src The address of the data.
			 * @param src_size The number of bytes under the data address.
			 * @returns The number of bytes written to the decoder.
			 */
			unsigned int Write(const void * src, unsigned int src_size) noexcept;
	}; /* class Decoder */

	Decoder& operator << (Decoder& decoder, unsigned char byte) noexcept;

} /* namespace utfx */

#endif /* UTFX_DECODER_HPP */

