#ifndef UTFX_VERSION_H
#define UTFX_VERSION_H

#define UTFX_VERSION_MAJOR 3
#define UTFX_VERSION_MINOR 0
#define UTFX_VERSION_PATCH 1
#define UTFX_VERSION_STRING "3.0.1"

#endif /* UTFX_VERSION_H */

