#ifndef UTFX_VERSION_H
#define UTFX_VERSION_H

#define UTFX_VERSION_MAJOR 3
#define UTFX_VERSION_MINOR 0
#define UTFX_VERSION_PATCH 0
#define UTFX_VERSION_STRING "3.0.0"

#endif /* UTFX_VERSION_H */

