#ifndef LIBUTF_VERSION_H
#define LIBUTF_VERSION_H

#define LIBUTF_VERSION_MAJOR 4
#define LIBUTF_VERSION_MINOR 0
#define LIBUTF_VERSION_PATCH 1
#define LIBUTF_VERSION_STRING "4.0.1"

#endif /* LIBUTF_VERSION_H */

